version: '3'
services:
  corenlp:
    build: .
    networks:
      - corenlpnet
    restart: always
    ports:
      - "9090:9090"
    container_name: corenlp
    environment:
      - JAVA_OPTS=-Xmx4g -Xms4g 

networks:
  corenlpnet:
